### ISSUE TITLE
publish/unpublish individual objects

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#169]
current functionality:
unpublish and publish collection and all child objects

use cases:
public collection unpublish single individual object
public collection publish single individual object that's unpublished
private collection keep selection of objects unpublished and publish rest of the entire collection

out of scope:
private collection publish individual object

**Comment by freyesdulib** [comment]
Completed ability to publish individual object.
TODO: work on unpublishing individual object.

**Comment by kimpham54** [comment]
batch public/private toggling of collections is possible

**Comment by kimpham54** [comment]
done. fernando to work on passing in api key for unpublished objects to view thumbnail
