### ISSUE TITLE
Add a date field to the index "display_record" of collection objects

### ISSUE THREAD

**Issue by jrynhart** [dulibrarytech/digitaldu-backend#197]
This should be similar or identical to a normal object's display_record "dates" field, which includes a nested "begin" field and/or "end" field, and an "expression" field.

This will allow the display of the collection's date data on the search results, and any other metadata displays

This will allow a daterange filter to be used on a set of search results that contain collection and normal objects

**Comment by freyesdulib** [comment]
Complete.  mappings changed and repository re-indexed.
