### ISSUE TITLE
account for videos that don't have derivatives

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#198]
Fernando noticed Duracloud errors in videos, turn off archivematica derivatives, errors for DIPs nothing to test against. try to detect two filetypes and skip backend check for those two filetypes or ping kaltura to see if the file is there -> certain files don’t get derivatives

**Comment by kimpham54** [comment]
Fernando to modify backend to Check that kaltura entry id exists if derivative is available and publish - if it doesn’t exist flag as error

**Comment by freyesdulib** [comment]
resolved.
