### ISSUE TITLE
script to do QA on object packages

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#200]
related to the ingest process. Script will be run on a collection to validate each package after the package script runs

Script should do the following: drill into folders, confirms a uri.txt in each folder, the following filetypes exist: tiff/wav/pdf maybe allow for others too, check that filenames conform to spec (A-Z, 0-9, ".", "-", "_" only), check for duplicate objects as based on URI, check for collection in repository

**Comment by freyesdulib** [comment]
workflow:
https://docs.google.com/document/d/1nqzQob2jw0QDhnFtRxBnEX1ighwUYtFP8kaSVrmWx30/edit#heading=h.cpjk7xji1wzb

**Comment by freyesdulib** [comment]
additional ideas for QA scripts

metadata - all attributes are constructed in elasticsearch, dates are valid
indexing - script to look at logs and get information about records not indexed and put that into QA script

**Comment by freyesdulib** [comment]
Check if fields are published on the ArchivesSpace side before ingesting.

**Comment by freyesdulib** [comment]
Ongoing.  Unit tests needed.

**Comment by freyesdulib** [comment]
Complete
