### ISSUE TITLE
archivesspace API errors when making too many requests for batch metadata updates

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#203]
412 code after making many requests to the API - 
Fernando finished the metadata batch update by collection, but there seems to be potential memory issues or thread issues every time you make API requests. wants to schedule updates where things don’t explode. server is fine but handling requests becomes an issue when there are too many consecutive ones. possible apache issues? not hardware issue but app related (issue was reproducible in local environment). maybe also look into cron jobs, scheduling updates on a monthly basis

**Comment by freyesdulib** [comment]
complete.  Worked around issue by importing 10 records at a time with each batch generating and destroying its own session token.  Added timer to allow archivesspace to throttle down CPU before next batch begins.  Cronjob is in place to run weekly.
