### ISSUE TITLE
enhancement requests for backend

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#205]
- add uuid field in imported objects https://librepo01-vlp.du.edu/dashboard/import/complete
- publish all in unpublished objects view

**Comment by kimpham54** [comment]
from kate: It's working, thank you! A future enhancement request that I think would be great would be the ability to do this as a batch with all of the objects in a given collection since we're often working to update the metadata in them in batches anyway, and finding individual/specific items to update in a given collection can be challenging if there are a) a lot of them and b) a lot of them have very similar metadata (i.e.  600 photos of the "Texas Building").. Also if you're updating multiple items in a collection, every time you update an item, the message that it's been updated kicks you back up to the top of the results list and you have to scroll back down to work with the next one in the list, which makes it take longer than it needs to. I think the ability to batch update all objects in a collection might help. These are tiny nitpicks, and are NOT time sensitive to fix! Thank you so much!

**Comment by freyesdulib** [comment]
complete
