### ISSUE TITLE
Draw.io diagram of architecture unavailable 

### ISSUE THREAD

**Issue by misilot** [dulibrarytech/digitaldu-backend#221]
Hi,

When I try to view [Digital Collections BETA Architecture](https://drive.google.com/open?id=1J-06znPbHNQkKQ9gOB22Vtv7Rj8xDExX) - diagram that shows how our ecosystem, the repository frontend and backend is a component of this system - Last Updated: 2019 May from the readme, it allows me to download the html file, but when it goes to draw.io I cannot view it. Is it possible to put a PDF of the architecture up? I am just trying to understand all the different pieces involved.

Thanks!

**Comment by kimpham54** [comment]
Here's a jpg version of the diagram:
![Diagram-v1 0 - Digital Collections BETA rearchitecture](https://user-images.githubusercontent.com/2915770/110023518-8164f200-7cea-11eb-86c2-29300b225a8e.jpg)

Presentation from Open Repositories 2019: https://docs.google.com/presentation/d/11Egf-yGyJ_1BW6NSU68y87HSvUYM2mxGsG4EcMySMxA/edit?usp=sharing

We're happy to have an online meeting with you some time if you have questions or want to learn more.

**Comment by freyesdulib** [comment]
jpg version made available.
