### ISSUE TITLE
Page reloads when after metadata is updated record is displayed in search results page.

### ISSUE THREAD

**Issue by freyesdulib** [dulibrarytech/digitaldu-backend#267]
Page refreshes after metadata is updated when record is displayed in search results page.

**Comment by kcrowe1981** [comment]
This appears to be fixed, I did a search on "Louis" and then unpublished and republished the first result (http://hdl.handle.net/10176/7546afdd-ed65-40e4-8260-de766574d85e) and nothing reloaded.

**Comment by freyesdulib** [comment]
resolved
