### ISSUE TITLE
create image workflow

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#27]
2018-08-20 16:29:47 - Kim Pham (Work notes)
 priority task to work on for the speccoll application

**Comment by freyesdulib** [comment]
Fernando: optimizing workflow, cleanup logging, more testing required
flag record and indicate if a datastream is missing
need large batches multiple collections for testing
Fernando to document what are the 5 or 6 things that makes up an object

**Comment by kimpham54** [comment]
awesome ready
