### ISSUE TITLE
JCRS ingest (Box 102) ingested compound objects not rendering properly in back end

### ISSUE THREAD

**Issue by kcrowe1981** [dulibrarytech/digitaldu-backend#293]
Box 102 of the Jewish Consumptives' Relief Society records contains multiple examples of the same issue, ingested items where all digital objects, digital object component records, and files in the SFTP package are correct and match, but the ingested file/record with a compound object does not render/show the files in each record that make up the compound object.

Ex: Louis Klebanoff #1241, pid: e387de50-9b0a-46b3-818d-3fe3b99681f5
handle: http://hdl.handle.net/10176/e387de50-9b0a-46b3-818d-3fe3b99681f5

Example image of Klebanoff<img width="628" alt="B002_PID_1241_Klebanoff" src="https://github.com/dulibrarytech/digitaldu-backend/assets/46686677/e034c0cb-7846-41e7-821d-cbcea0afdc09">

Samuel Simon #1270, pid: [2ee0510f-e183-4888-9132-b818d9ce9b2b
handle: http://hdl.handle.net/10176/2ee0510f-e183-4888-9132-b818d9ce9b2b

**Comment by freyesdulib** [comment]
Child object paths to DuraCloud are missing.

**Comment by kcrowe1981** [comment]
Is this a vendor issue (DuraCloud needs to do something)?

**Comment by freyesdulib** [comment]
No, it's a bug unrelated to the ingest process.  It appears to be caused by a bug in the metadata updates.  I'm going to disable it until the fixed version is in production.
