### ISSUE TITLE
Ability to run report and/or show all unpublished records in repository back end

### ISSUE THREAD

**Issue by kcrowe1981** [dulibrarytech/digitaldu-backend#294]
This is potentially an update/extension of this #284 on showing the last 30 days of ingests, but we're seeing enough records get ingested and slip by the publishing/QA process that having a way to see ALL unpublished records even as part of the options within the landing page. I do think this would require some discussion about what additional limiting features this kind of enhancement might also include (I'd say at least by collection, but maybe there are others).

**Comment by freyesdulib** [comment]
Each collection has an "unpublished objects" link that shows unpublished records in the collection.  Can you take a look and see if that meets your need?  Note that the recently ingested page shows the last 1,000 records and not the last 30days. (That was changed a few months ago)
<img width="1255" alt="Screen Shot 2024-04-12 at 2 35 03 PM" src="https://github.com/dulibrarytech/digitaldu-backend/assets/8998638/f514d802-ef43-403e-9590-3753f9b2c46f">

**Comment by kcrowe1981** [comment]
I think it probably would for now, most of the ingests at scale or where the work is dispersed between departments and records might sit unpublished longer are specific to a collection. If we ever get to do more heterogeneous (multiple collections, multiple records) ingests regularly we might want to revisit.

**Comment by freyesdulib** [comment]
Understood.

**Comment by kcrowe1981** [comment]
If this is a "potential, down the road" thing is it best to leave it as-is or close it?

**Comment by freyesdulib** [comment]
Definitely leave it.  The underlying code is already there.  We just need to load the data into another screen. Having a "bird's eye view" of unpublished records sounds more useful anyway.

**Comment by freyesdulib** [comment]
Complete.  Update Is in v1.9
