### ISSUE TITLE
meet with Duraspace to sort out two accounts

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#6]
2018-09-19 09:27:10 - Kim Pham (Work notes)
 kevin is working with duracloud on this i believe. to be completed when we successfully moved everything over to the new duracloud

**Comment by kimpham54** [comment]
fine now

**Comment by kimpham54** [comment]
actually not sure if fine. keeping open

**Comment by freyesdulib** [comment]
It's fine.
