### ISSUE TITLE
kill process/stop transfer feature

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#62]
kill transfer with logs
kill process and remove everything that's been 

hanging process or

**Comment by kimpham54** [comment]
out of scope to kill a transfer. e.g. if metadata needed to change or objects realized don't want to ingest

**Comment by kimpham54** [comment]
not for second release, hold off

**Comment by freyesdulib** [comment]
There doesn't appear to be a way to pause/stop the ingest process once archivematica begins the ingest process.
