### ISSUE TITLE
get 3 test objects from digital collections services

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#66]
@jackflaps need 3 test objects from DCS to test out archivesspace integration with repository:

3 images: 
Ingest structure

.
└── collection:pid/
    ├── imagetest/
    │   └── waynewhite.tif
    │   └── uri.txt

3 pdfs:

Ingest structure
.
└── collection:pid/
    ├── pdftest/
    │   └── readings.pdf
    │   └── uri.txt

**Comment by jackflaps** [comment]
I lied before, I'm going to send the archival object URIs because that's how you get the MODS records

**Comment by jackflaps** [comment]
files posted to sftp://libsftp01-vlp.du.edu/library/lib-sftp/image_test

**Comment by kimpham54** [comment]
thanks @jackflaps
