### ISSUE TITLE
archivesspace integration workflow

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#67]
@kimpham54 commented on [Thu Nov 29 2018](https://github.com/dulibrarytech/digitaldu-frontend/issues/76)
see https://gist.github.com/jackflaps/fb98f3a37ff0c34002b4ea29e1238dda for full details

## To create an object in the repository

Preconditions:
- Metadata record exists in archivesspace

1. Doug logs in to the backend repository
2. Doug ingests an image from the archivematica SFTP server using the ingest structure
collection:pid
-birdimage
-- birdimage.tiff
-- uri.txt

the image gets ingested and the following happens in the repository:
- image is indexed in elasticsearch
- generate SIP UUID
- generate simple pid url (for now, subject to change)
- generate .csv of all the images that are ingested that maps archive space URIs found in all uri.txts to SIP UUID
- repository grabs from archivesspace the metadata record using archspace API that creates a stream endpoint, our repository has a webhook to pull metadata, process and index into ElasticSearch

3. Kevin/Alice gets email of CSVs, runs python script to update archivespace records based on URI:UUID mapping. 
- Metadata record will be updated to contain SIP UUID of object in repository

Note: metadata does not get stored in duracloud.

DONE

## To create metadata in the repository:
Not possible. Must create record in Archivesspace

DONE

## To update the metadata in the repository:
NOTE: It is assumed that all metadata updates happen in ArchivesSpace. We do not plan to have direct editing of metadata in the repository itself.

pre-conditions
- Object already exists in the repository
- Object is represented by a digital_object record in ArchivesSpace whose identifier is an Archivematica SIP UUID

1. Doug goes into a metadata record in archivesspace and updates the record
2. Click on "Reindex in repository" button
ArchivesSpace/Repository processes the request:
ArchivesSpace generates MODS record
ArchivesSpace POSTs MODS record to Repository
Repository has webhook to pull MODS record and index into elasticsearch

DONE

## To update an object in the repository:
TBD, need to update archivesspace simultaneously

## To delete an object from the repository:
1. Doug deletes from archivesspace, record is gone
2. Doug deletes from repository by SIP UUID, object is gone and is no longer indexed in elasticsearch

**Comment by freyesdulib** [comment]
Fernando to work on updates for archivesspace, test updating records. Work with Kate/Alice/Kevin on this for testing

**Comment by kimpham54** [comment]
this is done. awesome work @freyesdulib
