### ISSUE TITLE
archivesspace response for image record in repository

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#68]
@jackflaps
can we get a parsed response of the metadata that you intend to put into the repository

include information about how you want titles and values to be mapped and indexed if different from the archivesspace response

lets start with an image, ideally the response will be appropriate for the images you select in https://github.com/dulibrarytech/digitaldu-backend/issues/66

**Comment by kimpham54** [comment]
@jackflaps - never mind, we dont need a parsed response. i forgot we are just going to use the ArchiveSpace API directly

**Comment by jackflaps** [comment]
It occurs to me that if you're going to query the ASpace API, we don't technically need MODS at all. If it's easier for you to read JSON into the index, I can look into how we can have the API return that instead

**Comment by kimpham54** [comment]
@jackflaps sounds good! we won't need MODS then. We'll just need a document of some sort to map the response we get from the API to fields you want to see in the repository

**Comment by jackflaps** [comment]
New plugin for this: https://github.com/duspeccoll/repository_sync

Dropped a sample JSON object in slack; will push the plugin out for testing by Monday
