### ISSUE TITLE
archivesspace integration - update metadata

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#76]
we need to develop the ability to update metadata from archivesspace into the repository. 

option 1 manual

1. editor goes into archivesspace and updates a record that has a an archivesspace found in the repository

2. editor saves the record

3. editor clicks on button in record that says 'update in repository' (this triggers a GET from the repository, _log the change in the repository and also send a message back in archivesspace?_)

(optional) editor receives notification in archivesspace that record has been updated in repository

4. editor goes to uri in repository and sees metadata update in repository

option 2 webhooks

1. editor goes into archivesspace and updates a record that has a an archivesspace found in the repository

2. editor saves the record (this triggers a POST, repository receives and processes the POST,  _log the change in the repository and also send a message back in archivesspace?_)

(optional) editor receives notification in archivesspace that record has been updated in repository

3. editor goes to uri in repository and sees metadata update in repository

@jackflaps wondering if webhooks currently exist for archivesspace every time a record is updated or if that's something that we would have to work on

**Comment by jackflaps** [comment]
there's an /update-feed API call that returns all of the records that have been updated since the last time a user called it, but nothing more active than that as far as I'm aware

**Comment by freyesdulib** [comment]
The back-end now makes use of the Archivesspace update-feed API to perform metadata updates.  Thanks Kevin.

**Comment by kimpham54** [comment]
done or single objects, pulls from archivesspace, updates local record and reindexes

**Comment by kimpham54** [comment]
working on bugs for compound objects, parts not being changed and breaking that process

**Comment by kimpham54** [comment]
done. note that compound ordering cannot be updated, to fix in future release or as patch
