### ISSUE TITLE
documentation master object

### ISSUE THREAD

**Issue by freyesdulib** [dulibrarytech/digitaldu-backend#77]
Fernando to document what are the 5 or 6 things that makes up an object (tn, uri, etc)

https://docs.google.com/document/d/1lQcEt3_slGvSKYmw3hKKGtm9HiLsLEytdbC7oEI0xVo/edit#heading=h.71bcvhai558w

**Comment by kimpham54** [comment]
updated https://docs.google.com/document/d/1lQcEt3_slGvSKYmw3hKKGtm9HiLsLEytdbC7oEI0xVo/edit#heading=h.71bcvhai558w, will add to readme.
