### ISSUE TITLE
support for OCR datastreams for image/pdf/book

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#78]
to discuss with @jackflaps

do we need to support OCR datastreams at the preservation level? or just in elasticsearch?

DCS beforehand ingest
archivematica look into for preservation
elasticsearch for PDFs - not in AIP or DIP

https://specialcollections.du.edu/object/codu:59480 has a FULL_TEXT datastream from islandora PDF

images/books may also have an OCR datastream

**Comment by freyesdulib** [comment]
This shouldn't be in the release milestone.
