### ISSUE TITLE
add hide feature using archivematica API

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#80]
hide "DELETE" transfers after ingest - right away or on a daily basis. apparently artefactual has a hide script that does it on a daily basis or every few hours but it doesn't matter

https://wiki.archivematica.org/Archivematica_API#Hide_2
https://wiki.archivematica.org/Archivematica_API#Hide

failed or rejected transfers should be logged

keep FAILED, REJECTED, USER_INPUT,  or PROCESSING transfers, clear away just the COMPLETE
complete transfers are also recorded in digitaldubackend

**Comment by freyesdulib** [comment]
Completed records are cleared/hidden after each object import.
