### ISSUE TITLE
Database error (socket.io broadcasts) 

### ISSUE THREAD

**Issue by freyesdulib** [dulibrarytech/digitaldu-backend#84]
[2019-04-04T07:13:33.616] [ERROR] default - ERROR: import queue database error
(node:71360) Warning: a promise was rejected with a non-error: [object String]
Unhandled rejection ERROR: import queue database error Error: select * from `tbl_duracloud_import_queue` where DATE(created) = CURRENT_DATE group by `sip_uuid` order by `created` desc - Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column ‘repo_queue.tbl_duracloud_import_queue.id’ which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by kimpham54** [comment]
done
