### ISSUE TITLE
collection metadata pull

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#86]

**Comment by jackflaps** [comment]
let me know by when you'll want a resource API call written, otherwise I'll get sidetracked by some other migration task and forget

**Comment by kimpham54** [comment]
@jackflaps probably best to do this now before preparing objects for migration because Fernando Wille need to work on this functionality

**Comment by kimpham54** [comment]
from @jackflaps 
repo integration plugin for archivesspace collections seems to be working: https://github.com/duspeccoll/repository_sync/tree/resources

I'll put it in production by the end of the week unless something major comes up while I'm testing it
so now we can pull collection-level metadata from archivesspace with just the URI whether the "collection" is actually a collection or if it's a series instead

**Comment by kimpham54** [comment]
done
