### ISSUE TITLE
download objects index link

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#97]
index to archivematica, make sure no security issues

**Comment by kimpham54** [comment]
moving out of release

some stray thoughts:
option 1: if we do this programmatically for audio/video use OS to download master objects through backend admin, stitcher tool
option 2: DCS has to go into archivematica to download large audio/video

video/audio can be downloaded via kaltura deriv, link to

**Comment by jrynhart** [comment]
look into how to download master files from backend. look into stitching directly in duracloud, maybe also linking to page in archivematica to download

**Comment by freyesdulib** [comment]
Login to Archivematica to download stored "AIP" packages.
