### ISSUE TITLE
time estimate for test ingest 700 objects

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#98]

**Comment by freyesdulib** [comment]
These are rough estimates based on ~ 3,000 ingested objects
Average tiff and pdf (a few MB to a couple of hundred MB) take between 2.5 to 3.5 minutes per object.  
Large files > 2GB (tiffs, audio, video) take approximately 12 hrs.  files => 4GB take about one day per object.  ffmpeg, compression and storage processes take a long time on large files as expected.

**Comment by jrynhart** [comment]
done
